server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pg_premium_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Godspeed}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SIGNING_SECRET:fallback_default_secret_key_for_local_compilation_passes_404E63}
  expiration: ${JWT_EXPIRATION_MS:86400000}