spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg_premium_db
    username: postgres
    password: Godspeed
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false